# Use root/example as user/password credentials
version: '3.3'

services:
  # db:
  #   image: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: 'db'
  #     MYSQL_ROOT_PASSWORD: password
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ./db_data:/var/lib/mysql
  
  backend:
    build: ./backend
    ports:
      - 3000:3000
    # depends_on:
    #   - db
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:3000
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
  