# Use root/example as user/password credentials
version: '3.3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_SECURE_FILE_PRIV: ""
    ports:
      - '3306:3306'
    expose:
      - '3306'
  populate:
    build: .
    command: python populate.py
    depends_on:
      - db
  
  backend:
    build: ./backend
    ports:
      - 3000:3000
    # depends_on:
    #   - db
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:3000
    networks:
      - app-network


networks:
  app-network:
    driver: bridge