version: '3.7'

networks:
  app-network:
    driver: bridge
  db-network:
    driver: bridge

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - 3306:3306
    networks:
      - db-network
  backend:
    build: ./backend
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - app-network
      - db-network
  frontend:
    build: ./frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:3000
    networks:
      - app-network